### ISSUE TITLE
Could include homepage URL in description

### ISSUE THREAD

**Issue by lurch** [resin-os/balena#42]
At the top of https://github.com/resin-os/balena where it says `Moby-based Container Engine for Embedded, IoT, and Edge uses`, it probably wouldn't hurt to also include the https://www.balena.io/ URL? :)

Also @craig-mulligan is it "correct" that `http://balena.io` redirects to `https://www.balena.io/` whereas `http://www.etcher.io` redirects to `https://etcher.io` ?
Edit: And `https://resin.io` links to `https://balena.io/` which then redirects to `https://www.balena.io/`
Of course this doesn't really matter, as the redirects all work fine, I was merely asking out of curiosity.

**Comment by craig-mulligan** [comment]
@lurch I'm not sure, I don't have access to see which is the root url, not to add redirects, this is a question for @brownjohnf.

**Comment by brownjohnf** [comment]
I can answer some of this, and have pinged Alison about adding the link to the github page.

**Comment by brownjohnf** [comment]
balena -> www.balena is intentional, for security reasons around shared cookies and subdomains vs apex domains. www.resin -> resin is because of google ranking and marketing concerns. Basically, the more we can keep under the root domain the better (that's my understanding). Same for etcher. Going forward I think all new sites/services will be on subdomains.

**Comment by alisondavis17** [comment]
Yes, we should add a link to https://www.balena.io/ in the top of the github repo. We could make the first mention of balena a URL.

**Comment by lurch** [comment]
Thanks Jack. So (in a nutshell) resin.io and etcher.io are served without a subdomain for "historical reasons" (which we can't now change without upsetting google), and from now on all new domains will be served from www.whatever ?

**Comment by brownjohnf** [comment]
That is my understanding, yes.

**Comment by brownjohnf** [comment]
And I've added the website to the github repo.

**Comment by lurch** [comment]
> And I've added the website to the github repo.

Cool :)
