### ISSUE TITLE
Support for RPi Zero

### ISSUE THREAD

**Issue by nmaas87** [resin-os/balena#52]
The Raspberry Pi Zero (W) does use the ARM v6L architecture. Trying to start balena on the RPi Zero W with the ARMv6 package results in an invalid machine instruction error. Maybe it needs to be recompiled to be compatible with RPi Zeros ARM processor version. I tried this on the latest Raspbian Stretch version and would be willing to try next / patached versions on the RPi to ensure a valid fix :)

**Comment by abymmathew** [comment]
It still fails with the latest balena

**Comment by nmaas87** [comment]
@abymmathew The version provided on the download site / balena.io is from 13.10.2017 and hence older than this issue. The issue has been already fixed and this issue can be closed. However, they did not create a new download version. You can try out the latest version by downloading the Rasperry Pi 1 version of resinOS ( https://resinos.io/#downloads-raspberrypi ) - flash it to an SDcard using etcher and use it an RPi Zero W without problems :)
