### ISSUE TITLE
Question: where is the Moby Summit presentation slides?

### ISSUE THREAD

**Issue by AkihiroSuda** [resin-os/balena#59]
Hi, could you upload the slides if not uploaded yet?

**Comment by alisondavis17** [comment]
Yes, we will track them down and share a link!

**Comment by alisondavis17** [comment]
hi @AkihiroSuda you can find the slides here: https://www.slideshare.net/resin_io/balena-a-mobybased-container-engine-for-iot

**Comment by AkihiroSuda** [comment]
thanks
