### ISSUE TITLE
Unable to stop or remove paused container

### ISSUE THREAD

**Issue by fignew** [resin-os/balena#75]
**Description**
Error response from Balena: You cannot remove a paused container 2fe4a0f0ad97ff011a7d624281a0e8ab7629e4316c1dae3ba470a16c92858c6d. Unpause and then stop the container before attempting removal or force remove

This is different from the behavior of Docker/Moby. The change they made to make it work can be found here: https://github.com/moby/moby/pull/34027/files

**Steps to reproduce the issue:**
1. Create container
2. Pause container
3. Attempt to stop or delete container

**Describe the results you received:**
Instead of stopping or removing the container Balena gives the message: "Error response from daemon: You cannot remove a paused container 2fe4a0f0ad97ff011a7d624281a0e8ab7629e4316c1dae3ba470a16c92858c6d. Unpause and then stop the container before attempting removal or force remove"

**Describe the results you expected:**
A stopped or deleted container. (Like what would be the case with Docker/Moby)

**Additional information you deem important (e.g. issue happens only occasionally):**
This error is triggered during a SaltStack build of a docker image.

**Output of `balena version`:**

```
Client:
 Version:      unknown-version
 API version:  1.31
 Go version:   go1.8
 Git commit:   unknown-commit
 Built:        unknown-buildtime
 OS/Arch:      linux/arm

Server:
 Version:      17.06.0-dev
 API version:  1.31 (minimum version 1.12)
 Go version:   go1.8
 Git commit:   748e0c102458bbab56e2b928fdffcbf41c8a870c
 Built:        Wed Jan 10 14:54:41 2018
 OS/Arch:      linux/arm
 Experimental: true

```

**Output of `balena info`:**

```
Containers: 5
 Running: 2
 Paused: 1
 Stopped: 2
Images: 10
Server Version: 17.06.0-dev
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 18
 Dirperm1 Supported: true
Logging Driver: journald
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan null
 Log: journald json-file
Swarm:
 NodeID:
 Is Manager: false
 Node Address:
Runtimes: bare runc
Default Runtime: runc
Init Binary: balena-init
containerd version:  (expected: 3addd840653146c90a254301d6c3a663c7fd6429)
runc version: 13e66eedaddfbfeda2a73d23701000e4e63b5471
init version: 949e6fa-dirty (expected: 949e6facb7738)
Kernel Version: 4.9.59
Operating System: Resin OS 2.9.6+rev1
OSType: linux
Architecture: armv7l
CPUs: 4
Total Memory: 875.8MiB
Name: thisthat
ID: ARLH:KM2S:ZW5S:5KIR:376M:YJVI:PWAP:SQSI:POZL:LEPG:VVMO:DRZS
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: No oom kill disable support
```

**Comment by petrosagg** [comment]
hey @fignew, this will be addressed once we merge https://github.com/resin-os/balena/pull/73 and release balena 17.12  that includes the commit you pointed to

**Comment by fignew** [comment]
Ok! Thanks so much :+1:
